
export const dataBase = [
    {
        id: 1,
        img: "../src/assets/images/cleaning.png",
        title: "Поддерживающая убока",
        info: [
            {
                id: 1,
                title: "Студия (22 м2) ",
                price: 100_000,
                timeComplete: 30,
            },

            {
                id: 2,
                title: "1-комнатная (31 м2) ",
                price: 120_000,
                timeComplete: 45,
            },
            {
                id: 3,
                title: "2-комнатная (47,6 м2) ",
                price: 150_000,
                timeComplete: 60,
            },
        ],
    },
    {
        id: 2,
        img: "../src/assets/images/GenralCleaning.png",
        title: "Генеральная уборка",
        info: [
            {
                id: 1,
                title: "Студия (22 м2) ",
                price: 100_000,
                timeComplete: 60,
            },

            {
                id: 2,
                title: "1-комнатная (31 м2) ",
                price: 120_000,
                timeComplete: 90,
            },
            {
                id: 3,
                title: "2-комнатная (47,6 м2) ",
                price: 150_000,
                timeComplete: 110,
            },
        ],
    },
    {
        id: 3,
        img: "../src/assets/images/WindowCleaning.png",
        title: "Мытьё комнатных окон",
        subTitle: "(с двух сторон)",
        info: [
            {
                id: 1,
                title: "Студия (22 м2) ",
                price: 35_000,
                timeComplete: 10,
            },

            {
                id: 2,
                title: "1-комнатная (31 м2) ",
                price: 35_000,
                timeComplete: 20,
            },
            {
                id: 3,
                title: "2-комнатная (47,6 м2) ",
                price: 35_000,
                timeComplete: 30,
            },
        ],
    },
    {
        id: 4,
        img: "../src/assets/images/extra_services.png",
        title: "Дополнительный услуги",
        info: [
            {
                id: 1,
                title: "Мойка секций шкафов  ",
                subTitle: "(внутри)",
                price: 20_000,
                timeComplete: 20,
            },
            {
                id: 2,
                title: "Мойка холодильника ",
                subTitle: "(внутри с разморозкой) ",
                price: 20_000,
                timeComplete: 20,
            },
            {
                id: 3,
                title: "Мойка микроволновой печи  ",
                subTitle: "(внутри)",
                price: 20_000,
                timeComplete: 15,
            },

            {
                id: 4,
                title: "Мойка посуды ",
                price: 30_000,
                timeComplete: 15,
            },
            {
                id: 5,
                title: "Раскладка одежды в гардероб ",
                subTitle: "(1 секция – 1 категория одежды) ",
                price: 15_000,
                timeComplete: 10,
            },
            {
                id: 6,
                title: "Замена постельного белья ",
                subTitle: "(комплект) ",
                price: 15_000,
                timeComplete: 10,
            },
            {
                id: 6,
                title: "Замена постельного белья ",
                subTitle: "(комплект) ",
                price: 15_000,
                timeComplete: 10,
            },
            {
                id: 7,
                title: "Стирка белья в стиральной машинке арендатора ",
                subTitle: "с развешиванием на сушилку (Стирка ( до 6 кг)) ",
                price: 20_000,
                timeComplete: 40,
            },
            {
                id: 8,
                title: "Химчистка мебели",
                subTitle: "( диван )",
                price: 75_000,
                timeComplete: 20,
            },
            {
                id: 9,
                title: "Химчистка мебели",
                subTitle: "( стул )",
                price: 25_000,
                timeComplete: 10,
            },
            {
                id: 10,
                title: "Химчистка мебели",
                subTitle: "( матрас )",
                price: 100_000,
                timeComplete: 30,
            },
            {
                id: 11,
                title: "Химчистка штор / тюля ",
                subTitle: "( со съемом )  ",
                price: 50_000,
                timeComplete: 20,
            },
            {
                id: 12,
                title: "Утюг + отпариватель ( парогенератор )",
                subTitle: "+ доска в аренду",
                price: 50_000,
                timeComplete: "аренда 60",
            },
            {
                id: 13,
                title: "Очистка противожировых металлических ",
                subTitle: "самонесущих фильтров кухонной вытяжки  ",
                price: 30_000,
                timeComplete: "неизвестно",
            },
            {
                id: 14,
                title: "Замена угольного фильтра против",
                subTitle: "запахов кухонной вытяжки",
                price: 30_000,
                timeComplete: "неизвестно",
            },
            {
                id: 15,
                title: "Стирка, глажка белья ",
                subTitle: "( 1 кг )",
                price: 30_000,
                timeComplete: 30,
            },
        ],
    },
    {
        id: 5,
        img: "../src/assets/images/extra_services_for_aparent.png",
        title: "Другие услуги в квартире",
        info: [
            {
                id: 1,
                title: "Уход за комнатным растениями ",
                subTitle: "( полив, опрыскивание )",
                price: 10_000,
                timeComplete: 10,
            },

            {
                id: 2,
                title: "Замена батареек в пульте",
                subTitle: "( комплект )",
                price: 30_000,
            },
            {
                id: 3,
                title: "Навеска штор / тюля",
                subTitle: "( полотно )",
                price: 15_000,
                timeComplete: 20,
            },
            {
                id: 4,
                title: "Будильник (звонок администратора ",
                subTitle: " в нужное время )",
                price: "бесплатно",
                timeComplete: "1 звонок ",
            },
            {
                id: 5,
                title: "Аренда пылесоса ",
                subTitle: " ( 2 часа )",
                price: 30_000,
                timeComplete: 60,
            },
            {
                id: 6,
                title: "Аренда обогревателя ",
                subTitle: " ( 2 часа )",
                price: 30_000,
                timeComplete: 1440,
            },
        ],
    },
    {
        id: 6,
        img: "../src/assets/images/water_services.png",
        title: "Доставка воды",
        info: [
            {
                id: 1,
                title: "Вода минеральная ",
                subTitle: "( Бут. 19 л. )",
                price: 25_000,
                timeComplete: "неизвестно",
            },

            {
                id: 2,
                title: "Помпа ручная ",
                price: 45_000,
                timeComplete: "неизвестно",
            },
            {
                id: 3,
                title: "Помпа электрическая",
                price: 55_000,
                timeComplete: "неизвестно",
            },
        ],
    },
    {
        id: 7,
        img: "../src/assets/images/Loading_services.png",
        title: "Погрузочно-разгрузочные работы и вынос негабаритного мусора",
        info: [
            {
                id: 1,
                title: "Крупногабаритные погрузо",
                subTitle: "-разгрузочные работы ",
                price: 100_000,
                timeComplete: 60,
            },

            {
                id: 2,
                title: "Малогабаритные погрузо",
                subTitle: "-разгрузочные работы ",
                price: 75_000,
                timeComplete: 30,
            },
            {
                id: 3,
                title: "Вынос бытового мусора ",
                subTitle: "( до 5 кг )",
                price: 25_000,
                timeComplete: 10,
            },
            {
                id: 4,
                title: "Вынос крупного негабаритного мусора ",
                subTitle:
                    "(превышающего 80 см. в длину или весом более 10 кг.)",
                price: 30_000,
                timeComplete: 15,
            },
        ],
    },
    {
        id: 8,
        img: "../src/assets/images/restoring_card.png",
        title: "Прочие услуги",
        info: [
            {
                id: 1,
                title: "Восстановление электронной карты доступа ",
                price: 50_000,
                timeComplete: "прийти в офис",
            },
        ],
    },
    {
        id: 9,
        img: "../src/assets/images/Water_supply_and_sewerage.png",
        title: "Водоснабжение и канализация ",
        info: [
            {
                id: 1,
                title: "  Консультация специалиста по водоснабжению ",
                price: "бесплатно",
                timeComplete: 15,
            },

            {
                id: 2,
                title: "Замена гибкой подводки к прибору ",
                price: 36_000,
                timeComplete: 30,
            },
            {
                id: 3,
                title: "Замена запорного крана ",
                price: 42_000,
                timeComplete: 30,
            },
            {
                id: 4,
                title: "Замена прокладки смесителя / сифона ",
                price: 39_000,
                timeComplete: 30,
            },
            {
                id: 5,
                title: "Уплотнение соединений ",
                price: 3_000,
                timeComplete: 30,
            },
            {
                id: 6,
                title: "Герметизация швов и примыканий ",
                price: 17_000,
                timeComplete: 60,
            },
            {
                id: 7,
                title: "Замена унитаза",
                price: 138_000,
                timeComplete: 60,
            },
            {
                id: 8,
                title: "Демонтаж унитаза",
                price: 138_000,
                timeComplete: 60,
            },
            {
                id: 9,
                title: "Замена умывальника ",
                price: 110_000,
                timeComplete: 60,
            },
            {
                id: 10,
                title: "Демонтаж умывальника ",
                price: 110_000,
                timeComplete: 30,
            },
            {
                id: 11,
                title: "Замена душевой кабины ",
                price: 550_000,
                timeComplete: 90,
            },
            {
                id: 12,
                title: "Демонтаж душевой кабины ",
                price: 138_000,
                timeComplete: 30,
            },
            {
                id: 13,
                title: "Замена арматуры сливного бачка ",
                price: 126_000,
                timeComplete: 30,
            },
            {
                id: 14,
                title: "Замена кухонного смесителя ",
                price: 77_000,
                timeComplete: 30,
            },
            {
                id: 15,
                title: "Замена смесителя умывальника ",
                price: 77_000,
                timeComplete: 30,
            },
            {
                id: 16,
                title: "Замена смесителя душевой кабины ",
                price: 77_000,
                timeComplete: 30,
            },
            {
                id: 17,
                title: "Ремонт шланга душа ",
                price: 44_000,
                timeComplete: 30,
            },
            {
                id: 18,
                title: "Замена шланга душа ",
                price: 44_000,
                timeComplete: 30,
            },
            {
                id: 19,
                title: "Замена крышки унитаза ",
                price: 49_000,
                timeComplete: 30,
            },
            {
                id: 20,
                title: "Регулировка сиденья к унитазу ",
                price: 38_000,
                timeComplete: 30,
            },
            {
                id: 21,
                title: "Прочистка засора канализационной сети внутри квартиры",
                price: 87_000,
                timeComplete: 60,
            },
            {
                id: 22,
                title: "Герметизация плинтуса ",
                price: 26_000,
                timeComplete: 30,
            },
            {
                id: 23,
                title: "Замена сифона к умывальнику, мойке ",
                price: 77_000,
                timeComplete: 30,
            },
            {
                id: 24,
                title: "Замена гофры к унитазу ",
                price: 44_000,
                timeComplete: 60,
            },
            {
                id: 25,
                title: "Герметизация поддона душевой кабины/",
                subTitle: "стенок душевой кабины по периметру",
                price: 38_000,
                timeComplete: 90,
            },
            {
                id: 27,
                title: "Установка / прочистка аэратора ",
                price: 27_000,
                timeComplete: 30,
            },  
        ],
    },
    {
        id: 10,
        img:"../src/assets/images/heating_services.png",
        title:"ОТОПЛЕНИЕ",
        info: [
            {
                id: 1,
                title: "Консультация специалиста  ",
                price:"бесплатно",
                timeComplete: 15,
            },

            {
                id: 2,
                title: "Развоздушивание радиатора ",
                price: 18_000,
                timeComplete: 30,
            },
            {
                id: 3,
                title: "Замена крана Маевского ",
                price: 44_000,
                timeComplete: 30,
            },
        ],
    },
    {
        id:11 ,
        img:"../src/assets/images/electrical_services.png",
        title:"ЭЛЕКТРОТЕХНИЧЕСКИЕ РАБОТЫ",
        info: [
            {
                id: 1,
                title: "Консультация специалиста ",
                price:"бесплатно",
                timeComplete: 15,
            },

            {
                id: 2,
                title: "Замена лампы потолочного светильника ",
                price: 82_000,
                timeComplete: 30,
            },
            {
                id: 3,
                title: "Замена влагозащитного встраиваемого светильника ",
                price: 82_000,
                timeComplete:30 ,
            },
            {
                id: 4,
                title: "Ремонт розетки/выключателя ",
                price: 40_000,
                timeComplete:60 ,
            },
            {
                id: 5,
                title: "Замена розетки/выключателя ",
                price: 40_000,
                timeComplete:30 ,
            },
            {
                id: 6,
                title: "Замена лампы освещения в холодильнике ",
                price: 20_000,
                timeComplete:30 ,
            },
            {
                id: 7,
                title: "Замена лампы освещения в кухонной вытяжке  ",
                price: 20_000,
                timeComplete:30 ,
            },
        ],
    },
    {
        id: 12,
        img:"../src/assets/images/carpently_services.png",
        title:"ПЛОТНИЦКИЕ РАБОТЫ ",
        info: [
            {
                id: 1,
                title: "Консультация специалиста ",
                price:"бесплатно",
                timeComplete: 15,
            },

            {
                id: 2,
                title: "Регулировка фурнитуры дверных блоков ",
                price: 60_000,
                timeComplete: 30,
            },
            {
                id: 3,
                title: "Регулировка фурнитуры шкафов ",
                price: 50_000,
                timeComplete: 30,
            },
            {
                id: 4,
                title: "Замена накладного или врезного замка на место ранее установленного (межкомнатного) ",
                price: 39_000,
                timeComplete: 30,
            },
             {
                id:5 ,
                title: "Монтаж держателя для лейки душа ",
                price: 22_000,
                timeComplete: 30,
            },
             {
                id:6 ,
                title: "Монтаж кронштейна под телевизор ",
                price: 22_000,
                timeComplete: 60,
            },
             {
                id:7 ,
                title: "Замена уплотнителя на дверях",
                subTitle:" (за одну створку) ",
                price: 30_000,
                timeComplete: 30,
            },
             {
                id: 8,
                title: "Замена врезного замка, дверных ручек межкомнатных дверей ",
                price: 125_000,
                timeComplete: 60,
            },
             {
                id:9 ,
                title: "Замена дверной ручки ",
                subTitle:"(меж) ",
                price: 125_000,
                timeComplete: 30,
            },
             {
                id: 10,
                title: "Регулировка входной двери ",
                price: 60_000,
                timeComplete: 30,
            },
             {
                id:11 ,
                title: "Ремонт мебели ",
                price: 40_000,
                timeComplete: "за 60",
            },
             {
                id:12 ,
                title: "Навеска картин ",
                price: 25_000,
                timeComplete: 30,
            },
             {
                id: 13,
                title: "Замена зеркала в ванной ",
                price: 110_000,
                timeComplete: 60,
            },
             {
                id: 14,
                title: "Сборка мебели простая ",
                subTitle:"(до 6 элементов) ",
                price: 110_000,
                timeComplete: 60,
            },
             {
                id: 14,
                title: "Сборка мебели средней сложности ",
                subTitle:"(от 6 до 16 элементов) ",
                price: 165_000,
                timeComplete: 90,
            },
             {
                id: 16,
                title: "Сборка мебели высокой сложности ",
                subTitle:"(от 16 элементов) ",
                price: 220_000,
                timeComplete: 120,
            },
             {
                id:17,
                title: "Монтаж зеркала  ",
                      subTitle:"(по комплектации)",
                price: 44_000,
                timeComplete: 30,
            },
             {
                id: 18,
                title: "Монтаж зеркала ",
                 subTitle:"(собственность Арендатора) ",
                price: 44_000,
                timeComplete: 30,
            },
             {
                id:19 ,
                title: "Сверление отверстий Ø до 20 мм ",
                price: 25_000,
                timeComplete: 30,
            },
             {
                id: 20,
                title: "Сверление отверстий Ø до 40 мм ",
                price: 25_000,
                timeComplete: 30,
            },
             {
                id: 21,
                title: "Установка ограничителя двери ",
                price: 25_000,
                timeComplete: 30,
            },
        ],
    },
    {
        id: 13,
        img:"../src/assets/images/painting_works_wall_services.png",
        title:"МАЛЯРНЫЕ РАБОТЫ: СТЕНЫ",
        info: [
            {
                id: 1,
                title: "Подготовительные работы (оклейка скотчем, укрытие поверхностей для защиты) ",
                price: 66_000,
                timeComplete:"∞",
            },

            {
                id: 2,
                title: "1-комнатная (31 м2) ",
                price: 66_000,
                timeComplete: "∞",
            },
            {
                id: 3,
                title: "Демонтаж штукатурки с механической очисткой от плесени ",
                price: 25_000,
                timeComplete:"кв.м ∞" ,
            },
            {
                id: 4,
                title: "Расшивка трещин ",
                price: 12_000,
                timeComplete:"пог.м.  ∞" ,
            },
            {
                id: 5,
                title: "Нанесение грунтовки глубокого проникновения ",
                price: 8_000,
                timeComplete:"кв.м.  ∞" ,
            },
            {
                id: 6,
                title: "Штукатурка швов, трещин, штроб ",
                price: 27_000,
                timeComplete:"кв.м.  ∞" ,
            },
            {
                id: 7,
                title: "Укладка плитки ",
                price: 110_000,
                timeComplete:"кв.м.  ∞" ,
            },
            {
                id: 8,
                title: "Затирка швов плитки ",
                price: 14_000,
                timeComplete:"кв.м.  ∞" ,
            },
            {
                id: 9,
                title: "Обработка от плесени ",
                price: 12_000,
                timeComplete:"кв.м.  ∞" ,
            },
            {
                id: 10,
                title: "Финишная шпатлевка  ",
                price: 33_000,
                timeComplete:"кв.м.  ∞" ,
            },
            {
                id: 11,
                title: "Окраска в 2 слоя вододисперсионной краской ",
                price: 30_000,
                timeComplete:"кв.м.  ∞" ,
            },
        ],
    },
    {
        id:14 ,
        img:"../src/assets/images/painting_works_ceilings_services.png",
        title:"МАЛЯРНЫЕ РАБОТЫ: ПОТОЛОК",
        info: [
            {
                id: 1,
                title: "Демонтаж светильников потолочных  ",
                price: 25_000,
                timeComplete: "∞",
            },

            {
                id: 2,
                title: "Монтаж светильников потолочных ",
                price: 25_000,
                timeComplete: "∞",
            },
            {
                id: 3,
                title: "Устройство каркаса для установки гипсокартона на потолок ",
                subTitle:"(1 уровень) ",
                price: 73_000,
                timeComplete:"кв.м.  ∞",
            },
            {
                id: 4,
                title: "Устройство гипсокартонного потолка ",
                subTitle:"(1 уровень) ",
                price: 60_000,
                timeComplete:"кв.м.  ∞",
            },
            {
                id: 5,
                title: "Расшивка трещин  ",
                price: 12_000,
                timeComplete:"пог.м.  ∞",
            },
            {
                id: 6,
                title: "Штукатурка швов (трещин)   ",
                price: 27_000,
                timeComplete:"пог.м.  ∞",
            },
            {
                id: 7,
                title: "Финишная шпатлевка ",
                price: 33_000,
                timeComplete:"кв.м.  ∞",
            },
            {
                id: 7,
                title: "Грунтовка  ",
                price: 13_000,
                timeComplete:"кв.м.  ∞",
            },
            {
                id: 8,
                title: "ГрунтовкаОкраска в 2 слоя",
                price: 13_000,
                timeComplete:"кв.м.  ∞",
            },
        ],
    },
    {
        id: 15,
        img:"../src/assets/images/painting_works_floor_services.png",
        title:"МАЛЯРНЫЕ РАБОТЫ: ПОЛ ",
        info: [
            {
                id: 1,
                title: "Гидроизоляция",
                price: 33_000,
                timeComplete:"кв.м.  ∞",
            },

            {
                id: 2,
                title: "Укладка плитки ",
                price: 110_000,
                timeComplete:"кв.м.  ∞",
            },
            {
                id: 3,
                title: "Затирка швов плитки ",
                price: 14_000,
                timeComplete:"кв.м.  ∞",
            },
            {
                id: 4,
                title: "Демонтаж плитки и стяжки ",
                price: 50_000,
                timeComplete:"кв.м.  ∞",
            },
            {
                id: 5,
                title: "Демонтаж плинтуса МДФ ",
                price: 10_000,
                timeComplete:"пог.м.  ∞",
            },
            {
                id: 4,
                title: "Монтаж плинтуса МДФ ",
                price: 50_000,
                timeComplete:"пог.м.  ∞",
            },
        ],
    }
];
